#!/usr/bin/env bash

testOutput="$(diff out <(./prog.out < in))"
if [ -z "$testOutput" ]; then
    echo "Successfully passed test case"
    exit 0
else
    echo "EXPECTED OUTPUT"
    cat out
    echo "YOUR OUTPUT"
    ./prog.out < in
    exit 1
fi
